[package]
name = "hmac-drbg"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Pure Rust implementation of Hmac DRBG."
license = "Apache-2.0"

[dependencies]
digest = "0.6"
generic-array = "0.8"
hmac = "0.4"

[dev-dependencies]
sha2 = "0.6"